import { getOnlineHint } from "../api";
import { CACHE_KEYS, readCache, writeCache } from "../offline/cache";
import bundledManifest from "./manifest.bundled.json";
import type { AssetManifest } from "./types";

/**
 * Where the asset manifest comes from, in priority order.
 *
 * 1. The local cache, written after the last successful fetch. This is what the
 *    second and every subsequent launch reads, which is why startup needs no
 *    network at all.
 * 2. The bundled snapshot below, so even a first launch that is offline still
 *    knows every asset's CDN URL and can stream art on demand rather than
 *    showing placeholders forever.
 * 3. The CDN, refreshed in the background once the UI is already interactive.
 */

/** Regenerated by `scripts/build-assets.py` — do not hand-edit. */
export const BUNDLED_MANIFEST = bundledManifest as AssetManifest;

export const MANIFEST_URL =
  process.env.EXPO_PUBLIC_ASSET_MANIFEST_URL ??
  `${BUNDLED_MANIFEST.baseUrl.replace(/\/+$/, "")}/manifest.json`;

/**
 * Structural guard. A CDN can return an error page, a truncated body or a stale
 * half-written file with a 200, and feeding that to the downloader would either
 * crash a render or wipe a perfectly good install record.
 */
export function isValidManifest(value: unknown): value is AssetManifest {
  if (!value || typeof value !== "object") return false;
  const m = value as Partial<AssetManifest>;
  if (typeof m.baseUrl !== "string" || !m.baseUrl) return false;
  if (!Array.isArray(m.assets) || m.assets.length === 0) return false;
  return m.assets.every(
    (a) =>
      a &&
      typeof a.key === "string" &&
      a.key.length > 0 &&
      typeof a.path === "string" &&
      a.path.length > 0 &&
      typeof a.sha256 === "string" &&
      typeof a.bytes === "number" &&
      a.bytes >= 0,
  );
}

/**
 * Fetch the manifest straight from the CDN.
 *
 * Deliberately *not* routed through `apiClient` in `services/api.ts`. That
 * helper is built for our own backend: it forces `Content-Type: application/json`
 * and `credentials: "include"`, retries against `http://localhost:5000` under
 * `__DEV__`, and — the real problem — intercepts 401 by clearing `auth_role` and
 * redirecting to `/login`. A CDN hiccup must never be able to sign a user out.
 *
 * It does reuse `getOnlineHint()` so a known-offline app doesn't burn the
 * timeout budget on a request that cannot succeed.
 */
export async function fetchRemoteManifest(timeoutMs = 8000): Promise<AssetManifest> {
  if (!getOnlineHint()) {
    const error = new Error("Offline — manifest fetch skipped") as Error & { isOffline: boolean };
    error.isOffline = true;
    throw error;
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(MANIFEST_URL, {
      method: "GET",
      signal: controller.signal,
      // Let the CDN's own validators work; jsDelivr caches branch URLs ~12h.
      headers: { Accept: "application/json" },
    });
    if (!response.ok) {
      throw new Error(`Manifest fetch failed: HTTP ${response.status}`);
    }
    const parsed: unknown = await response.json();
    if (!isValidManifest(parsed)) {
      throw new Error("Manifest fetch returned a malformed document");
    }
    return parsed;
  } finally {
    clearTimeout(timer);
  }
}

export async function readCachedManifest(): Promise<AssetManifest | null> {
  const cached = await readCache<AssetManifest>(CACHE_KEYS.ASSET_MANIFEST);
  if (cached && isValidManifest(cached.data)) return cached.data;
  return null;
}

export async function writeCachedManifest(manifest: AssetManifest): Promise<void> {
  await writeCache(CACHE_KEYS.ASSET_MANIFEST, manifest);
}

/**
 * Best-known manifest without touching the network: last fetch, else the
 * bundled snapshot. Always returns something, so the registry can always be
 * primed with CDN URLs.
 */
export async function loadLocalManifest(): Promise<AssetManifest> {
  return (await readCachedManifest()) ?? BUNDLED_MANIFEST;
}
